name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update -qq
      - run: sudo apt-get install -y -qq
          meson wayland-scanner libwayland-dev
          libcairo2-dev libpango1.0-dev
          libsdl2-dev libevdev-dev
      - run: meson setup build
      - run: meson compile -C build
